# Generated by Django 4.2.5 on 2023-12-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='content',
            field=models.CharField(default='상품 구성 : ', max_length=100),
        ),
    ]
