# Generated by Django 4.2.5 on 2023-11-28 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dib',
            fields=[
                ('dibId', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='일반', max_length=255)),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants_app.restaurant')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userId', 'storeId')},
            },
        ),
    ]
