# Generated by Django 4.2.5 on 2023-11-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0002_dib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuoption',
            name='status',
            field=models.CharField(default='활성화', max_length=255),
        ),
    ]
