# Generated by Django 5.0.4 on 2024-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0004_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='return_date',
            field=models.DateTimeField(auto_now=True, verbose_name='반납일자'),
        ),
    ]
