# Generated by Django 5.0.4 on 2024-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0005_alter_qrcode_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='생성일'),
        ),
    ]
