# Generated by Django 5.0.4 on 2024-06-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0006_alter_qrcode_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='return_date',
            field=models.DateTimeField(verbose_name='반납일자'),
        ),
    ]
