# Generated by Django 4.2.5 on 2023-11-09 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(choices=[('CASH', '현금'), ('CREDIT_CARD', '신용카드'), ('KAKAO_PAY', '카카오페이')], max_length=20)),
                ('totalPrice', models.PositiveIntegerField()),
                ('requestMsg', models.CharField(default='(없음)', max_length=255)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('reOrderTime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACCEPTING_ORDER', '주문 접수 중'), ('ORDER_COMPLETE', '주문 완료'), ('DELIVERY', '배달 중'), ('DELIVERY_COMPLETE', '배달 완료')], default='ACCEPTING_ORDER', max_length=255)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderMenu', to='orders_app.order')),
            ],
        ),
    ]
