# Generated by Django 4.2.5 on 2023-11-28 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='일반', max_length=255)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.BigAutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(max_length=255)),
                ('totalPrice', models.PositiveIntegerField()),
                ('requestMsg', models.CharField(default='(없음)', max_length=255)),
                ('status', models.CharField(default='정상', max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='restaurants_app.restaurant')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cartItemId', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='일반', max_length=255)),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_app.cart')),
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants_app.menu')),
                ('menuOptionId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants_app.menuoption')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants_app.restaurant')),
            ],
        ),
    ]
