# Generated by Django 4.2.5 on 2023-11-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartId',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='orders_app.cart'),
        ),
    ]
