# Generated by Django 4.2.5 on 2023-11-09 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0002_alter_menu_createddate_alter_menu_modifieddate_and_more'),
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurantId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='restaurants_app.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='menu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurants_app.menu'),
            preserve_default=False,
        ),
    ]
