# Generated by Django 4.2.5 on 2023-11-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_order_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_app.cart'),
        ),
    ]
