# Generated by Django 4.2.5 on 2023-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0003_alter_order_cartid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("주문 확인", "주문 확인"),
                    ("조리중", "조리중"),
                    ("배달중", "배달중"),
                    ("배달 완료", "배달 완료"),
                ],
                default="주문 확인",
                max_length=255,
            ),
        ),
    ]
