# Generated by Django 4.2.5 on 2023-11-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_alter_order_cartid'),
        ('reviews_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='orderId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to='orders_app.order'),
        ),
    ]
