# Generated by Django 4.2.5 on 2023-11-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_alter_order_cartid'),
        ('reviews_app', '0002_reviews_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to='orders_app.order'),
        ),
    ]
